### ISSUE TITLE
че за пиздец

### ISSUE THREAD

**Issue by tailsjs** [XidMods05/brawl-core-v2#5]
че за пиздец

**Comment by XidMods05** [comment]
> че за пиздец

Пруфай

**Comment by tailsjs** [comment]
![image](https://user-images.githubusercontent.com/49571184/185586523-e0e987c8-3718-4a82-850c-2c12c78a0a09.png)
![image](https://user-images.githubusercontent.com/49571184/185586580-c8318a41-5a62-4d21-ad2a-b10e5ca0d93a.png)
![image](https://user-images.githubusercontent.com/49571184/185586759-173032c9-81cd-40c8-a162-6373cc8ad4e8.png)
![image](https://user-images.githubusercontent.com/49571184/185586821-92680873-4869-4935-8b97-a4b0c81e5fdc.png)
![image](https://user-images.githubusercontent.com/49571184/185586959-85218ada-2f9d-41e4-9b8d-b9d9175fdb1d.png)
вопросы?

**Comment by tailsjs** [comment]
и это только поверхность

**Comment by tailsjs** [comment]
также отдельно я затрону readme.odt

.md формат для ебланов наверна

**Comment by XidMods05** [comment]
> и это только поверхность

Нихуя не понял зачем ты файлы показал просто, ты глубже покажи

**Comment by XidMods05** [comment]
> также отдельно я затрону readme.odt
> 
> .md формат для ебланов наверна

Ааа ну только к названиям файлов и можем придраться. А к коду слабо.

**Comment by tailsjs** [comment]
да погоди блять

**Comment by XidMods05** [comment]
> ладно, хочешь разбора кода
> 
> Жду малыш!!!!!

**Comment by XidMods05** [comment]
> ![IMG_20220818_234805_202](https://user-images.githubusercontent.com/99066334/185588741-89fec0e3-adce-42a4-86d7-a6f769ee65c1.jpg)

Ааа понимаю

**Comment by tailsjs** [comment]
это то, что автор называет антиддосом. точнее, пытается.
![image](https://user-images.githubusercontent.com/49571184/185589557-ec4ac7c4-4f2e-4206-a73c-2a33499a99d2.png)
![image](https://user-images.githubusercontent.com/49571184/185589688-b5e61b2a-a191-4563-8b8e-7d9ab36b3b11.png)
сразу первый вопрос зачем в ядре вообще антиддос? ядро это основа сервера, где ты просто должен показать человеку как нужно писать логику для пакетов/как их отправлять. конечно, ты молодец, справился с этим. но зачем в ядро сувать это недоподобие антиддоса. 

также можно заметить, что в нашем "ядре" есть санкции на страны, которые не находятся в массиве `["RU", "AZ", "KZ", "AM", "BY", "KG", "MD", "TJ", "UZ"]` нужно ли оно человеку, который собирается писать сервер с нуля? автор считает, что да.
ещё: self.adminlist. зачем оно вообще нужно? а всё понял, чтобы сервер в консоли выдавал `Admin logged into PlayerServer! IP - 1.1.1.1`
если бы это был бы сервер, а не ядро, тогда бы я этот момент даже трогать не стал бы. 

то, что я перечислил выше - это только PlayerServer.py, который запускает сторону сервера для игроков.
и, переходя к этому, в ядре есть ещё и AdminServer.py, который по сути отличается только строчкой 
```py
if addr[0] in self.adminlist:
                                print("Admin authorized!")
                                continue
                            else:
                                socket.close()
                                break
```
можно спросить: а есть ли отличия в Admin и Player?
ну, таковых нет. кроме той строчки и импортов
тогда зачем сувать сука два сервера в одно ядро? для того, чтобы разраб мог запустить параллельно два сервера? ну тип классно, но опять же, в ядре это нахуй не надо.
файлы [Player|Admin]Handler.py нужны просто чтобы перенести нас на [Player|Admin]Server.py. почему бы тогда не перенести весь код из Server.py в Handler.py? наверна так как предлагает работать нам автор выглядит профессиональней.

дальше идёт main.py, через который мы и должны запускать сервер
сервер адекватного человека: при вводе `python3 main.py` у нас сразу запускается сервер
сервер курильщика:
![image](https://user-images.githubusercontent.com/49571184/185593056-7d3c812c-68b1-45a1-bb4c-1497ac973366.png)

1. опять же, перенести код сюда из [Player|Admin]Server.py.
2. `Not main or launcher hack! - " + __name__` - это защиты чтоли или что? 
3. time.sleep(2) для того, чтобы сделать вид что всё запускается

я уже не доёбываюсь что ты класс в классе в классе делаешь, ибо не удивляюсь

![image](https://user-images.githubusercontent.com/49571184/185593607-51ba0674-362c-4528-94bc-edcd51f0ac8b.png)
какаято ебатория с коммандами. да даже если представить что это как-то нужно, то это можно вшить и в сам сервер.
3. time.sleep(2) для того, чтобы сделать вид что всё запускается

я вообще не понимаю ты сервер блять делаешь или ядро

также код подпизжен у ромашки.
ромашка
![image](https://user-images.githubusercontent.com/49571184/185594620-0037f088-a3e4-4c0a-b1be-6b5a2a16ed54.png)
ты
![image](https://user-images.githubusercontent.com/49571184/185594664-1800929e-0663-4ae4-ab4f-e2415c96066c.png)

ромашка
![image](https://user-images.githubusercontent.com/49571184/185594791-e3aa4fb0-3f32-4606-a6e7-b90ee7fc665e.png)
ты
![image](https://user-images.githubusercontent.com/49571184/185594818-5b78e39e-b4d9-4450-ad99-aa756323ebbe.png)

ромашка
![image](https://user-images.githubusercontent.com/49571184/185594925-a9ed3b94-2e5a-4012-ad83-55a46f6fac48.png)
ты
![image](https://user-images.githubusercontent.com/49571184/185595036-e01542c5-2074-46b6-8ed1-6f24742e1c65.png)
![image](https://user-images.githubusercontent.com/49571184/185595087-6eb70841-b1e3-48c4-8fae-8aa38eaf63a2.png)

ромашка
![image](https://user-images.githubusercontent.com/49571184/185595198-447fd3be-fa51-4e3c-b454-9b058908f9fa.png)
ты
![image](https://user-images.githubusercontent.com/49571184/185595228-a177ae2b-25d3-4e4f-bd6b-7b55211e7a4b.png)

как назвать когда ты своё ядро делаешь на чужом ядре?

"AntiDDos will protect your server from an attack of (~seven terabytes) per second." -- brawl-core-v2
"Этот сурс был сделан для средне-профессиональных участников SC-RE." -- brawl-core

**Comment by XidMods05** [comment]
> это то, что автор называет антиддосом. точнее, пытается. ![image](https://user-images.githubusercontent.com/49571184/185589557-ec4ac7c4-4f2e-4206-a73c-2a33499a99d2.png) ![image](https://user-images.githubusercontent.com/49571184/185589688-b5e61b2a-a191-4563-8b8e-7d9ab36b3b11.png) сразу первый вопрос зачем в ядре вообще антиддос? ядро это основа сервера, где ты просто должен показать человеку как нужно писать логику для пакетов/как их отправлять. конечно, ты молодец, справился с этим. но зачем в ядро сувать это недоподобие антиддоса.
> 
> также можно заметить, что в нашем "ядре" есть санкции на страны, которые не находятся в массиве `["RU", "AZ", "KZ", "AM", "BY", "KG", "MD", "TJ", "UZ"]` нужно ли оно человеку, который собирается писать сервер с нуля? автор считает, что да. ещё: self.adminlist. зачем оно вообще нужно? а всё понял, чтобы сервер в консоли выдавал `Admin logged into PlayerServer! IP - 1.1.1.1` если бы это был бы сервер, а не ядро, тогда бы я этот момент даже трогать не стал бы.
> 
> то, что я перечислил выше - это только PlayerServer.py, который запускает сторону сервера для игроков. и, переходя к этому, в ядре есть ещё и AdminServer.py, который по сути отличается только строчкой
> 
> ```python
> if addr[0] in self.adminlist:
>                                 print("Admin authorized!")
>                                 continue
>                             else:
>                                 socket.close()
>                                 break
> ```
> 
> можно спросить: а есть ли отличия в Admin и Player? ну, таковых нет. кроме той строчки и импортов тогда зачем сувать сука два сервера в одно ядро? для того, чтобы разраб мог запустить параллельно два сервера? ну тип классно, но опять же, в ядре это нахуй не надо. файлы [Player|Admin]Handler.py нужны просто чтобы перенести нас на [Player|Admin]Server.py. почему бы тогда не перенести весь код из Server.py в Handler.py? наверна так как предлагает работать нам автор выглядит профессиональней.
> 
> дальше идёт main.py, через который мы и должны запускать сервер сервер адекватного человека: при вводе `python3 main.py` у нас сразу запускается сервер сервер курильщика: ![image](https://user-images.githubusercontent.com/49571184/185593056-7d3c812c-68b1-45a1-bb4c-1497ac973366.png)
> 
> 1. опять же, перенести код сюда из [Player|Admin]Server.py.
> 2. `Not main or launcher hack! - " + __name__` - это защиты чтоли или что?
> 3. time.sleep(2) для того, чтобы сделать вид что всё запускается
> 
> я уже не доёбываюсь что ты класс в классе в классе делаешь, ибо не удивляюсь
> 
> ![image](https://user-images.githubusercontent.com/49571184/185593607-51ba0674-362c-4528-94bc-edcd51f0ac8b.png) какаято ебатория с коммандами. да даже если представить что это как-то нужно, то это можно вшить и в сам сервер. 3. time.sleep(2) для того, чтобы сделать вид что всё запускается
> 
> я вообще не понимаю ты сервер блять делаешь или ядро
> 
> также код подпизжен у ромашки. ромашка ![image](https://user-images.githubusercontent.com/49571184/185594620-0037f088-a3e4-4c0a-b1be-6b5a2a16ed54.png) ты ![image](https://user-images.githubusercontent.com/49571184/185594664-1800929e-0663-4ae4-ab4f-e2415c96066c.png)
> 
> ромашка ![image](https://user-images.githubusercontent.com/49571184/185594791-e3aa4fb0-3f32-4606-a6e7-b90ee7fc665e.png) ты ![image](https://user-images.githubusercontent.com/49571184/185594818-5b78e39e-b4d9-4450-ad99-aa756323ebbe.png)
> 
> ромашка ![image](https://user-images.githubusercontent.com/49571184/185594925-a9ed3b94-2e5a-4012-ad83-55a46f6fac48.png) ты ![image](https://user-images.githubusercontent.com/49571184/185595036-e01542c5-2074-46b6-8ed1-6f24742e1c65.png) ![image](https://user-images.githubusercontent.com/49571184/185595087-6eb70841-b1e3-48c4-8fae-8aa38eaf63a2.png)
> 
> ромашка ![image](https://user-images.githubusercontent.com/49571184/185595198-447fd3be-fa51-4e3c-b454-9b058908f9fa.png) ты ![image](https://user-images.githubusercontent.com/49571184/185595228-a177ae2b-25d3-4e4f-bd6b-7b55211e7a4b.png)
> 
> как назвать когда ты своё ядро делаешь на чужом ядре?
> 
> "AntiDDos will protect your server from an attack of (~seven terabytes) per second." -- brawl-core-v2 "Этот сурс был сделан для средне-профессиональных участников SC-RE." -- brawl-core

Ты просто нихуя не шаришь, зачем это ядро было сделано поэтому и какаешь свою дичь

**Comment by vanyadev228** [comment]
пиздец

**Comment by tailsjs** [comment]
я тебе уже всё расписал. 
![image](https://user-images.githubusercontent.com/49571184/185596579-354e46a2-1b09-49e5-ae86-d823361e26bb.png)

**Comment by XidMods05** [comment]
> > это то, что автор называет антиддосом. точнее, пытается. ![image](https://user-images.githubusercontent.com/49571184/185589557-ec4ac7c4-4f2e-4206-a73c-2a33499a99d2.png) ![image](https://user-images.githubusercontent.com/49571184/185589688-b5e61b2a-a191-4563-8b8e-7d9ab36b3b11.png) сразу первый вопрос зачем в ядре вообще антиддос? ядро это основа сервера, где ты просто должен показать человеку как нужно писать логику для пакетов/как их отправлять. конечно, ты молодец, справился с этим. но зачем в ядро сувать это недоподобие антиддоса.
> > также можно заметить, что в нашем "ядре" есть санкции на страны, которые не находятся в массиве `["RU", "AZ", "KZ", "AM", "BY", "KG", "MD", "TJ", "UZ"]` нужно ли оно человеку, который собирается писать сервер с нуля? автор считает, что да. ещё: self.adminlist. зачем оно вообще нужно? а всё понял, чтобы сервер в консоли выдавал `Admin logged into PlayerServer! IP - 1.1.1.1` если бы это был бы сервер, а не ядро, тогда бы я этот момент даже трогать не стал бы.
> > то, что я перечислил выше - это только PlayerServer.py, который запускает сторону сервера для игроков. и, переходя к этому, в ядре есть ещё и AdminServer.py, который по сути отличается только строчкой
> > ```python
> > if addr[0] in self.adminlist:
> >                                 print("Admin authorized!")
> >                                 continue
> >                             else:
> >                                 socket.close()
> >                                 break
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > можно спросить: а есть ли отличия в Admin и Player? ну, таковых нет. кроме той строчки и импортов тогда зачем сувать сука два сервера в одно ядро? для того, чтобы разраб мог запустить параллельно два сервера? ну тип классно, но опять же, в ядре это нахуй не надо. файлы [Player|Admin]Handler.py нужны просто чтобы перенести нас на [Player|Admin]Server.py. почему бы тогда не перенести весь код из Server.py в Handler.py? наверна так как предлагает работать нам автор выглядит профессиональней.
> > дальше идёт main.py, через который мы и должны запускать сервер сервер адекватного человека: при вводе `python3 main.py` у нас сразу запускается сервер сервер курильщика: ![image](https://user-images.githubusercontent.com/49571184/185593056-7d3c812c-68b1-45a1-bb4c-1497ac973366.png)
> > 
> > 1. опять же, перенести код сюда из [Player|Admin]Server.py.
> > 2. `Not main or launcher hack! - " + __name__` - это защиты чтоли или что?
> > 3. time.sleep(2) для того, чтобы сделать вид что всё запускается
> > 
> > я уже не доёбываюсь что ты класс в классе в классе делаешь, ибо не удивляюсь
> > ![image](https://user-images.githubusercontent.com/49571184/185593607-51ba0674-362c-4528-94bc-edcd51f0ac8b.png) какаято ебатория с коммандами. да даже если представить что это как-то нужно, то это можно вшить и в сам сервер. 3. time.sleep(2) для того, чтобы сделать вид что всё запускается
> > я вообще не понимаю ты сервер блять делаешь или ядро
> > также код подпизжен у ромашки. ромашка ![image](https://user-images.githubusercontent.com/49571184/185594620-0037f088-a3e4-4c0a-b1be-6b5a2a16ed54.png) ты ![image](https://user-images.githubusercontent.com/49571184/185594664-1800929e-0663-4ae4-ab4f-e2415c96066c.png)
> > ромашка ![image](https://user-images.githubusercontent.com/49571184/185594791-e3aa4fb0-3f32-4606-a6e7-b90ee7fc665e.png) ты ![image](https://user-images.githubusercontent.com/49571184/185594818-5b78e39e-b4d9-4450-ad99-aa756323ebbe.png)
> > ромашка ![image](https://user-images.githubusercontent.com/49571184/185594925-a9ed3b94-2e5a-4012-ad83-55a46f6fac48.png) ты ![image](https://user-images.githubusercontent.com/49571184/185595036-e01542c5-2074-46b6-8ed1-6f24742e1c65.png) ![image](https://user-images.githubusercontent.com/49571184/185595087-6eb70841-b1e3-48c4-8fae-8aa38eaf63a2.png)
> > ромашка ![image](https://user-images.githubusercontent.com/49571184/185595198-447fd3be-fa51-4e3c-b454-9b058908f9fa.png) ты ![image](https://user-images.githubusercontent.com/49571184/185595228-a177ae2b-25d3-4e4f-bd6b-7b55211e7a4b.png)
> > как назвать когда ты своё ядро делаешь на чужом ядре?
> > "AntiDDos will protect your server from an attack of (~seven terabytes) per second." -- brawl-core-v2 "Этот сурс был сделан для средне-профессиональных участников SC-RE." -- brawl-core
> 
> Ты просто нихуя не шаришь, зачем это ядро было сделано поэтому и какаешь свою дичь

Команды нужны для того чтобы показать пример людям как можно организовать их.
Полностью отдельный админ сервер нужен для примера как можно организовать второй сервер. В данном случае на отдельном порте ибо у людей нет денег на другую машину.

**Comment by XidMods05** [comment]
> я тебе уже всё расписал. ![image](https://user-images.githubusercontent.com/49571184/185596579-354e46a2-1b09-49e5-ae86-d823361e26bb.png)

А чё это твой ромашка слился и забанил меня?))) Сразу бы сказал в лицо я ему предлагал Баттл.

**Comment by XidMods05** [comment]
> > я тебе уже всё расписал. ![image](https://user-images.githubusercontent.com/49571184/185596579-354e46a2-1b09-49e5-ae86-d823361e26bb.png)
> 
> А чё это твой ромашка слился и забанил меня?))) Сразу бы сказал в лицо я ему предлагал Баттл.

Пахнет сосанием.

**Comment by tailsjs** [comment]
![image](https://user-images.githubusercontent.com/49571184/185597027-538dc096-aa17-4c3f-92aa-ae7963333f1c.png)

**Comment by XidMods05** [comment]
> ![image](https://user-images.githubusercontent.com/49571184/185597027-538dc096-aa17-4c3f-92aa-ae7963333f1c.png)

А это мне сказали так делать

**Comment by tailsjs** [comment]
![image](https://user-images.githubusercontent.com/49571184/185597232-7c9a0e65-12bb-42e8-8afe-89dac5864651.png)

**Comment by tailsjs** [comment]
![image](https://user-images.githubusercontent.com/49571184/185597276-9f8815f8-e471-41b6-9d0c-6a914f922a1c.png)
"а че твой ромашка меня в чс кинул"

**Comment by XidMods05** [comment]
> это

По поводу антиддоса, он был выставлен сюда чтобы некоторые люди сосали пенисок.

**Comment by tailsjs** [comment]
> > это
> 
> По поводу антиддоса, он был выставлен сюда чтобы некоторые люди сосали пенисок.

в ядре это не нужно

**Comment by XidMods05** [comment]
> 

А пусть он сюда зайдет, позови его, ты не справляешься.

**Comment by XidMods05** [comment]
> ![image](https://user-images.githubusercontent.com/49571184/185597276-9f8815f8-e471-41b6-9d0c-6a914f922a1c.png) "а че твой ромашка меня в чс кинул"

Позови своего ромашку сюда, пускай зайдет, ты уже не справляешься.

**Comment by XidMods05** [comment]
> > > это
> > 
> > 
> > По поводу антиддоса, он был выставлен сюда чтобы некоторые люди сосали пенисок.
> 
> в ядре это не нужно

Это не ядро, это пример ядра

**Comment by tailsjs** [comment]
а помоему наоборот, ты не справляешься.
я могу его позвать, но смысл, когда ничего нового ты не скажешь

**Comment by XidMods05** [comment]
> а помоему наоборот, ты не справляешься. я могу его позвать, но смысл, когда ничего нового ты не скажешь

Это вы ничего нового не скажете. Как клоуны начали оскать код без знания для чего он был создан.

**Comment by XidMods05** [comment]
> > > > > это
> > > > 
> > > > 
> > > > По поводу антиддоса, он был выставлен сюда чтобы некоторые люди сосали пенисок.
> > > 
> > > 
> > > в ядре это не нужно
> > 
> > 
> > Это не ядро, это пример ядра
> 
> ![image](https://user-images.githubusercontent.com/49571184/185597691-079a8053-83de-48f1-acb3-33c7dd2eb8d5.png)

А чё вы там в ЛС сосетесь один не вывез позвал второго. Второй наследовал поведение первого. Понятно.

**Comment by tailsjs** [comment]
![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)

**Comment by XidMods05** [comment]
> ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)

А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.

**Comment by XidMods05** [comment]
> > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> 
> А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.

Что ты как слитый вообще 🤡

**Comment by RomashkaTea** [comment]
ждали???

**Comment by XidMods05** [comment]
> ждали???

Очень!!!

**Comment by tailsjs** [comment]
> > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> 
> А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.

мы до сих пор не понимаем: это ядро или пример ядра

**Comment by XidMods05** [comment]
> > ждали???
> 
> Очень!!!

Все уже давно поняли, тот факт, что вы сосетесь там все под предлогом "крутой тимы", а на самом деле один соснул у другого и так по кругу. Ладно это не в тему.

**Comment by tailsjs** [comment]
одно ты пишешь, что ядро, тут, что пример

**Comment by XidMods05** [comment]
> > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > 
> > 
> > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> 
> мы до сих пор не понимаем: это ядро или пример ядра

Пример.

**Comment by XidMods05** [comment]
> > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > 
> > > 
> > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > 
> > 
> > мы до сих пор не понимаем: это ядро или пример ядра
> 
> Пример.

А написано что ядро чтобы разозлить одного чела

**Comment by tailsjs** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > > 
> > > > 
> > > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > > 
> > > 
> > > мы до сих пор не понимаем: это ядро или пример ядра
> > 
> > 
> > Пример.
> 
> А написано что ядро чтобы разозлить одного чела

ты сейчас пытаешься выпутаться из грязевой ямы или как

**Comment by XidMods05** [comment]
> а помоему наоборот, ты не справляешься. я могу его позвать, но смысл, когда ничего нового ты не скажешь

Вы прост

**Comment by XidMods05** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > > > 
> > > > > 
> > > > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > > > 
> > > > 
> > > > мы до сих пор не понимаем: это ядро или пример ядра
> > > 
> > > 
> > > Пример.
> > 
> > 
> > А написано что ядро чтобы разозлить одного чела
> 
> ты сейчас пытаешься выпутаться из грязевой ямы или как

Нет. Я сейчас расскажу подождите.

**Comment by RomashkaTea** [comment]
1. ты не справляешься нихуя, тейлс расписал всё, ты просто ответил что это дичь, а почему - ???
2. это не ядро, это уже сервер, в ядре должно быть просто как работать с протоколом, антиддос он по желанию, это уже к ядру не относится никак (и что ты подразумеваешь под "пример ядра"?)
3. "вы просто не знаете для чего оно создано", так чел, об этом нигде не указано, скажи тогда для чего))

**Comment by XidMods05** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > > > > 
> > > > > > 
> > > > > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > > > > 
> > > > > 
> > > > > мы до сих пор не понимаем: это ядро или пример ядра
> > > > 
> > > > 
> > > > Пример.
> > > 
> > > 
> > > А написано что ядро чтобы разозлить одного чела
> > 
> > 
> > ты сейчас пытаешься выпутаться из грязевой ямы или как
> 
> Нет. Я сейчас расскажу подождите.

Есть такой чел "унка" он имеет команду BrawlDdos, эта команда как и сам унка наш, враг, "наш" потому , что их Тима враг моей Тимы. И они вечно нас задирают, и я сделал ядро, которое полностью блокирует и отклоняет их атаки, чтобы их ддос не наносил вреда серверам которые юзают в виде ядра, мое примерное ядро. Примерное ядро, потому, что есть много ненужных функций для кого то, а для кого то они могут быть очень нужные. Вы писали по ограничения стран - это было сделано для того, чтобы унка не ддосил сервер например китайским ботнетом. А вообще первая версия ядра была сделана за несколько минут с кода ромашки. Это я уже потом сделал в2, где больше функций. Вот такие дела.

**Comment by XidMods05** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > > 
> > > > 
> > > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > > 
> > > 
> > > мы до сих пор не понимаем: это ядро или пример ядра
> > 
> > 
> > Пример.
> 
> А написано что ядро чтобы разозлить одного ч

**Comment by XidMods05** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/49571184/185598021-4662239c-a667-428f-aa74-2c0f46949f57.png)
> > > > > > > 
> > > > > > > 
> > > > > > > А пускай тебе и отвечает тейлс. Кому написал пусть тот и отвечает.
> > > > > > 
> > > > > > 
> > > > > > мы до сих пор не понимаем: это ядро или пример ядра
> > > > > 
> > > > > 
> > > > > Пример.
> > > > 
> > > > 
> > > > А написано что ядро чтобы разозлить одного чела
> > > 
> > > 
> > > ты сейчас пытаешься выпутаться из грязевой ямы или как
> > 
> > 
> > Нет. Я сейчас расскажу подождите.
> 
> Есть такой чел "унка" он имеет команду BrawlDdos, эта команда как и сам унка наш, враг, "наш" потому , что их Тима враг моей Тимы. И они вечно нас задирают, и я сделал ядро, которое полностью блокирует и отклоняет их атаки, чтобы их ддос не наносил вреда серверам которые юзают в виде ядра, мое примерное ядро. Примерное ядро, потому, что есть много ненужных функций для кого то, а для кого то они могут быть очень нужные. Вы писали по ограничения стран - это было сделано для того, чтобы унка не ддосил сервер например китайским ботнетом. А вообще первая версия ядра была сделана за несколько минут с кода ромашки. Это я уже потом сделал в2, где больше функций. Вот такие дела.

Отвечайте!

**Comment by RomashkaTea** [comment]
унка помоему вообще долбаёб который ничё не может

**Comment by XidMods05** [comment]
> унка помоему вообще долбаёб который ничё не может

Он себе в тиму нормальных челов взял.

**Comment by vanyadev228** [comment]
оа
